domain: nhsengland.github.io
url: https://nhsengland.github.io
baseurl: /DataScience/SignPost
repository: nhsengland/DataScience-SignPost
title: NHSE Data Science SignPost
description: Links to our data science resources
email: datascience@nhs.net
github_username: nhsengland
plugins:
  - jemoji
