- title: Example 1
  link: https://github.com/nhsengland/example1
  stage: Complete
  badge1: tag1
  badge2: tag2
  badge3: tag3
  description: Description
  author: Author

- title: Example 2
  link: https://github.com/nhsengland/example2
  stage: Delivery
  badge1: tag1
  badge2: tag2
  badge3: tag3
  description: Description
  author: Author

- title: Example 3
  link: https://github.com/nhsengland/example3
  stage: Delivery
  badge1: tag1
  badge2: tag2
  badge3: tag3
  description: Description
  author: Author

- title: Example 4
  link: https://github.com/nhsengland/example4
  stage: Discovery
  badge1: tag1
  badge2: tag2
  badge3: tag3
  description: Description
  author: Author